### ISSUE TITLE
Script error - Update Check Runs

### ISSUE THREAD

**Issue by jagoodhand** [imjohnbo/ok-to-test#21]
Thanks for putting this together, it's really useful. I've been experiencing a couple of (what I imagine are) permission errors related to the GitHub App configuration. Are there some additional permissions that need to be granted beyond those stated below?

```
default_permissions:
  contents: :write
  metadata: :read
```

This script: https://github.com/imjohnbo/ok-to-test/blob/474c02cafe14327d1a60febb7eb375f5935a430e/.github/workflows/integration.yml#L52-L73

Fails with this error for me:
```
2023-03-05T18:53:26.8384989Z RequestError [HttpError]: Resource not accessible by integration
2023-03-05T18:53:26.8387986Z     at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:6803:21
2023-03-05T18:53:26.8388365Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-03-05T18:53:26.8388932Z     at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15099:16), <anonymous>:13:26)
2023-03-05T18:53:26.8389463Z     at async main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15198:20) {
2023-03-05T18:53:26.8389745Z   status: 403,
2023-03-05T18:53:26.8389922Z   response: {
2023-03-05T18:53:26.8390378Z     url: 'https://api.github.com/repos/GoodhandSolutions/terraform-snowflake-playground/check-runs/11775549491',
2023-03-05T18:53:26.8391081Z     status: 403,
2023-03-05T18:53:26.8391282Z     headers: {
2023-03-05T18:53:26.8391572Z       'access-control-allow-origin': '*',
2023-03-05T18:53:26.8392544Z       'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
2023-03-05T18:53:26.8393279Z       connection: 'close',
2023-03-05T18:53:26.8393538Z       'content-encoding': 'gzip',
2023-03-05T18:53:26.8393865Z       'content-security-policy': "default-src 'none'",
2023-03-05T18:53:26.8394227Z       'content-type': 'application/json; charset=utf-8',
2023-03-05T18:53:26.8394548Z       date: 'Sun, 05 Mar 2023 18:53:26 GMT',
2023-03-05T18:53:26.8394962Z       'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
2023-03-05T18:53:26.8395324Z       server: 'GitHub.com',
2023-03-05T18:53:26.8395714Z       'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
2023-03-05T18:53:26.8396063Z       'transfer-encoding': 'chunked',
2023-03-05T18:53:26.8396408Z       vary: 'Accept-Encoding, Accept, X-Requested-With',
2023-03-05T18:53:26.8396746Z       'x-content-type-options': 'nosniff',
2023-03-05T18:53:26.8397024Z       'x-frame-options': 'deny',
2023-03-05T18:53:26.8397350Z       'x-github-api-version-selected': '2022-11-28',
2023-03-05T18:53:26.8397678Z       'x-github-media-type': 'github.v3',
2023-03-05T18:53:26.8398039Z       'x-github-request-id': '86C4:60B2:2DCE608:5F0BA85:6404E526',
2023-03-05T18:53:26.8398348Z       'x-ratelimit-limit': '1000',
2023-03-05T18:53:26.8398628Z       'x-ratelimit-remaining': '980',
2023-03-05T18:53:26.8398911Z       'x-ratelimit-reset': '1678044246',
2023-03-05T18:53:26.8399189Z       'x-ratelimit-resource': 'core',
2023-03-05T18:53:26.8399470Z       'x-ratelimit-used': '20',
2023-03-05T18:53:26.8400037Z       'x-xss-protection': '0'
2023-03-05T18:53:26.8400235Z     },
2023-03-05T18:53:26.8400407Z     data: {
2023-03-05T18:53:26.8400810Z       message: 'Resource not accessible by integration',
2023-03-05T18:53:26.8403050Z       documentation_url: 'https://docs.github.com/rest/reference/checks#update-a-check-run'
2023-03-05T18:53:26.8403371Z     }
2023-03-05T18:53:26.8403527Z   },
2023-03-05T18:53:26.8403684Z   request: {
2023-03-05T18:53:26.8403938Z     method: 'PATCH',
2023-03-05T18:53:26.8404396Z     url: 'https://api.github.com/repos/GoodhandSolutions/terraform-snowflake-playground/check-runs/11775549491',
2023-03-05T18:53:26.8404722Z     headers: {
2023-03-05T18:53:26.8405028Z       accept: 'application/vnd.github.-preview+json',
2023-03-05T18:53:26.8405475Z       'user-agent': 'actions/github-script octokit-core.js/3.6.0 Node.js/16.16.0 (linux; x64)',
2023-03-05T18:53:26.8405836Z       authorization: 'token [REDACTED]',
2023-03-05T18:53:26.8406169Z       'content-type': 'application/json; charset=utf-8'
2023-03-05T18:53:26.8406411Z     },
2023-03-05T18:53:26.8406688Z     body: '{"status":"completed","conclusion":"success"}',
2023-03-05T18:53:26.8407009Z     request: { agent: [Agent], hook: [Function: bound bound register] }
2023-03-05T18:53:26.8407248Z   }
2023-03-05T18:53:26.8407404Z }
2023-03-05T18:53:26.8437830Z ##[error]Unhandled error: HttpError: Resource not accessible by integration
```

Similarly the dispatching action, raises warnings for: `Failed to set reaction on comment ID 1455172514.`

Are these just user errors on my part or is it something else?

PS. I think the action versions need to be updated to prevent warnings being raised about the Node version. I can raise a PR for that.

**Comment by jagoodhand** [comment]
Worked out what the issue was. The `GITHUB_TOKEN` needed additional permissions (read/write) in Settings > Actions > General > Workflow Permissions (or could be done more granularly in the Workflow YAML). May be worth updating the docs to include this?

**Comment by imjohnbo** [comment]
Thanks for the issue report and PR! 😍

I think a couple of things are going on:
- The built-in `GITHUB_TOKEN`'s defaults were [recently changed to read-only](https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/), so explicit `write` permissions are helpful in the workflow, as you indicate [here](https://github.com/imjohnbo/ok-to-test/pull/22/files#diff-82454b2fc887e9985b9348b8f3bca03d2f839645a4c3ba1f3f850014d7da5c8bR24-R26) (or the defaults could be set at the [enterprise, organization, or repo level](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)). `GITHUB_TOKEN` is technically a special GitHub App installation access token generated by GitHub Actions but is unrelated to the other installation access token we generate [here](https://github.com/imjohnbo/ok-to-test/blob/474c02cafe14327d1a60febb7eb375f5935a430e/.github/workflows/ok-to-test.yml#L18-L23) and optionally use [here](https://github.com/imjohnbo/ok-to-test/blob/474c02cafe14327d1a60febb7eb375f5935a430e/.github/workflows/ok-to-test.yml#L30).
- The documentation of this workflow is out of date, as you [also indicate](https://github.com/imjohnbo/ok-to-test/issues/21#issuecomment-1455197706)! Would you be willing to open a separate PR for that? 🙏

**Comment by jagoodhand** [comment]
> The documentation of this workflow is out of date, as you https://github.com/imjohnbo/ok-to-test/issues/21#issuecomment-1455197706! Would you be willing to open a separate PR for that? 🙏

Sure. I'll adjust the docs to mention the GITHUB_TOKEN permissions. I'll also explicitly mention that it is ok to use 'example.com' type urls when creating the GitHub app. When I was creating my app, I wasn't sure that it would be ok to use URLs that didn't resolve, or that I didn't own. I noticed #12 also referenced this, so thought it may be worth bulking the docs out a bit on this if that is OK?
